import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.

public class Solution {
    public static void main(String[] args) {
        System.out.println(findTheDifference("asyd","asdyy"));
    }
    public static char findTheDifference(String s, String t) {
        char value1 = 0;
        for (char c : s.toCharArray()) {
            value1 ^= c;
        }
        for (int c : t.toCharArray()) {
            value1 ^= c;
        }
        return value1;
    }
}
